name: PIV_code_ORI
channels:
  - anaconda
  - conda-forge 
dependencies:
  - cudatoolkit=11.2
  - cudnn=8.2
  - python=3.8
  - jupyter
  - matplotlib= 3.7
  - pip 
  - pip:
      - tensorflow==2.8.4
      - sleap[pypi]==1.3.3
      - tables==3.8.0
      - openpyxl
      - tqdm
      - seaborn==0.13.2